"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GtxTissueExpression = void 0;
class GtxTissueExpression {
    constructor() {
        this.adipose_subcutaneous = 0;
        this.adipose_visceral_omentum = 0;
        this.adrenal_gland = 0;
        this.artery_aorta = 0;
        this.artery_coronary = 0;
        this.artery_tibial = 0;
        this.bladder = 0;
        this.brain_amygdala = 0;
        this.brain_anterior_cingulate_cortex_ba24 = 0;
        this.brain_caudate_basal_ganglia = 0;
        this.brain_cerebellar_hemisphere = 0;
        this.brain_cerebellum = 0;
        this.brain_cortex = 0;
        this.brain_frontal_cortex_ba9 = 0;
        this.brain_hippocampus = 0;
        this.brain_hypothalamus = 0;
        this.brain_nucleus_accumbens_basal_ganglia = 0;
        this.brain_putamen_basal_ganglia = 0;
        this.brain_spinal_cord_cervical_c_1 = 0;
        this.brain_substantia_nigra = 0;
        this.breast_mammary_tissue = 0;
        this.cells_ebv_transformed_lymphocytes = 0;
        this.cells_transformed_fibroblasts = 0;
        this.cervix_ectocervix = 0;
        this.cervix_endocervix = 0;
        this.colon_sigmoid = 0;
        this.colon_transverse = 0;
        this.esophagus_gastroesophageal_junction = 0;
        this.esophagus_mucosa = 0;
        this.esophagus_muscularis = 0;
        this.fallopian_tube = 0;
        this.heart_atrial_appendage = 0;
        this.heart_left_ventricle = 0;
        this.kidney_cortex = 0;
        this.liver = 0;
        this.lung = 0;
        this.minor_salivary_gland = 0;
        this.muscle_skeletal = 0;
        this.nerve_tibial = 0;
        this.ovary = 0;
        this.pancreas = 0;
        this.pituitary = 0;
        this.prostate = 0;
        this.skin_not_sun_exposed_suprapubic = 0;
        this.skin_sun_exposed_lower_leg = 0;
        this.small_intestine_terminal_ileum = 0;
        this.spleen = 0;
        this.stomach = 0;
        this.testis = 0;
        this.thyroid = 0;
        this.uterus = 0;
        this.vagina = 0;
        this.whole_blood = 0;
    }
}
exports.GtxTissueExpression = GtxTissueExpression;
//# sourceMappingURL=GtxTissueExpression.js.map